spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:h2:tcp://localhost/~/point-system
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#      show_sql: true
        format_sql: true
logging.level:
  org.hibernate.SQL: debug
    #  org.hibernate.type: tracespring:

jwt:
  token:
    secret-key: ejclzmzlkslkpqoalzmklsdmaldadqwieqwiodjklncmdsalkdjalsjcklzczmnndasdasdjhd
  access-token:
    expire-length: 1800000

#spring:
#  output:
#    ansi:
#      enabled: always
#  datasource:
#    url: jdbc:mysql://localhost:3306/point-system?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
#    username: root
#    password: 1234
#    database-platform: org.hibernate.dialect.MySQL57Dialect
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
##      show_sql: true
#        format_sql: true
#logging.level:
#  org.hibernate.SQL: debug
#    #  org.hibernate.type: trace